# Generated by Django 5.2.15 on 2026-06-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/', verbose_name='Resim')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Kampanya Menüsü',
                'verbose_name_plural': 'Kampanya Menüleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Mobil formatında video (MP4 önerilir). Scroll animasyonunda kullanılır.', upload_to='landing/', verbose_name='Video Dosyası')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Landing Video',
                'verbose_name_plural': 'Landing Videolar',
            },
        ),
        migrations.CreateModel(
            name='PromoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Promosyon Popup Aktif')),
            ],
            options={
                'verbose_name': 'Promosyon Ayarları',
                'verbose_name_plural': 'Promosyon Ayarları',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_enabled', models.BooleanField(default=True, help_text='Kampanya menüsü zaman diliminde gösterilsin mi?', verbose_name='Kampanya Aktif')),
                ('campaign_start', models.TimeField(default='12:30', help_text='Örn: 12:30', verbose_name='Kampanya Başlangıç Saati')),
                ('campaign_end', models.TimeField(default='16:30', help_text='Örn: 16:30', verbose_name='Kampanya Bitiş Saati')),
                ('site_title', models.CharField(default='BIG APPLE PUB', max_length=100, verbose_name='Site Başlığı')),
                ('tagline', models.CharField(default='Taze, bol ve sipariş üzerine!', max_length=200, verbose_name='Alt Başlık')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('group', models.CharField(choices=[('food', 'Yiyecek'), ('drinks', 'İçecek'), ('other', 'Diğer')], default='food', help_text='Yiyecek mi, içecek mi?', max_length=10, verbose_name='Grup')),
                ('icon', models.CharField(blank=True, default='', help_text='Opsiyonel emoji, örn: 🍔', max_length=10, verbose_name='İkon (emoji)')),
                ('parent', models.ForeignKey(blank=True, help_text='Bu kategori başka bir kategorinin alt kategorisiyse seçin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='menu.category', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (TL)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Resim')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Menü Ürünü',
                'verbose_name_plural': 'Menü Ürünleri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(max_length=50, verbose_name='Miktar / Boy')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='menu.menuitem', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Boy / Fiyat',
                'verbose_name_plural': 'Boy / Fiyatlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PromoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='promo_images/', verbose_name='Resim')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link_to_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category', verbose_name='Bağlantılı Kategori')),
            ],
            options={
                'verbose_name': 'Promosyon Resmi',
                'verbose_name_plural': 'Promosyon Resimleri',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
