# Generated by Django 4.2.16 on 2025-11-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="price",
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty",
                    models.CharField(
                        blank=True,
                        help_text="For Example: 4 cl, 33 cl, 1 lt",
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["price"],
            },
        ),
    ]
