# Generated by Django 4.2.16 on 2025-11-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_remove_menuitem_price_alter_menuitem_name_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
